### PR TITLE
Compile ES2015 code

### PR DESCRIPTION
**Pull request by sugarshin**
Plz check this PR.

ref: https://github.com/kevva/url-regex/issues/27

### CODE REVIEW

**Comment by kevva** [comment]
`npm install --save url-regex@^3.2.0`

**Comment by sugarshin** [comment]
Thanks, but v3.2.0 is not included [this](https://github.com/kevva/url-regex/commit/1feb53f570a39a9867c241253ee751114da42900) commit. can you please update ?

**Comment by SamVerschueren** [comment]
This won't be the first and the last project dropping support for older Node.js versions and thus dropping support for older browsers. I'm not sure if possible, but I think it is. It might be an idea to just let Babel (or whatever you are using) to transpile this dependency for you. Have a look at the Babel `ignore` option.

**Comment by tunnckoCore** [comment]
> This won't be the first and the last project dropping support for

@SamVerschueren  Agree. But is it so needed here and for such modules? For just one const and arrow? Come on.

[Should We Use ECMAScript 2015 (AKA "ES6")?](https://github.com/dwyl/goodparts#should-we-use-ecmascript-2015-aka-es6) - et al https://github.com/dwyl/goodparts README is awesome read.

j2c

**Pull request closed without merging**
